/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProjectType = {
    _id: string
    _type: 'projectType'
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    slug?: Slug
}

export type Brand = {
    _id: string
    _type: 'brand'
    _createdAt: string
    _updatedAt: string
    _rev: string
    name?: string
    slug?: Slug
}

export type Personality = {
    _id: string
    _type: 'personality'
    _createdAt: string
    _updatedAt: string
    _rev: string
    name?: string
    slug?: Slug
}

export type Post = {
    _id: string
    _type: 'post'
    _createdAt: string
    _updatedAt: string
    _rev: string
    name?: string
    imageUrl?: string
    postedAt?: string
}

export type StyleUp = {
    _id: string
    _type: 'styleUp'
    _createdAt: string
    _updatedAt: string
    _rev: string
    name?: string
    image?: {
        asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
    }
}

export type Project = {
    _id: string
    _type: 'project'
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    client?: string
    date?: string
    slug?: Slug
    projectType?: Array<{
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'projectType'
    }>
    featured?: boolean
    personalities?: Array<{
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'personality'
    }>
    brands?: Array<{
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'brand'
    }>
    gallery?: Array<{
        asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
    }>
    videos?: Array<{
        asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
        }
        media?: unknown
        thumbnail?: {
            asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
        }
        _type: 'file'
        _key: string
    }>
    videoUrls?: Array<{
        url?: string
        thumbnail?: {
            asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
        }
        _type: 'videoUrlItem'
        _key: string
    }>
    coverImage?: {
        asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
    }
    previewClip?: {
        asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
        }
        media?: unknown
        _type: 'file'
    }
    description?: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
        }>
        style?: 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
    }>
    credits?: Array<{
        role?: string
        name?: string
        link?: string
        _type: 'credit'
        _key: string
    }>
    orderRank?: string
}

export type Contact = {
    _id: string
    _type: 'contact'
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    email?: string
    instagram?: string
}

export type About = {
    _id: string
    _type: 'about'
    _createdAt: string
    _updatedAt: string
    _rev: string
    title?: string
    image?: {
        asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
    }
    bio?: string
}

export type Settings = {
    _id: string
    _type: 'settings'
    _createdAt: string
    _updatedAt: string
    _rev: string
    seo?: {
        description?: string
    }
    sidebarFilters?: {
        showPersonalities?: boolean
        showBrands?: boolean
    }
}

export type SanityImagePaletteSwatch = {
    _type: 'sanity.imagePaletteSwatch'
    background?: string
    foreground?: string
    population?: number
    title?: string
}

export type SanityImagePalette = {
    _type: 'sanity.imagePalette'
    darkMuted?: SanityImagePaletteSwatch
    lightVibrant?: SanityImagePaletteSwatch
    darkVibrant?: SanityImagePaletteSwatch
    vibrant?: SanityImagePaletteSwatch
    dominant?: SanityImagePaletteSwatch
    lightMuted?: SanityImagePaletteSwatch
    muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
    _type: 'sanity.imageDimensions'
    height?: number
    width?: number
    aspectRatio?: number
}

export type SanityImageHotspot = {
    _type: 'sanity.imageHotspot'
    x?: number
    y?: number
    height?: number
    width?: number
}

export type SanityImageCrop = {
    _type: 'sanity.imageCrop'
    top?: number
    bottom?: number
    left?: number
    right?: number
}

export type SanityFileAsset = {
    _id: string
    _type: 'sanity.fileAsset'
    _createdAt: string
    _updatedAt: string
    _rev: string
    originalFilename?: string
    label?: string
    title?: string
    description?: string
    altText?: string
    sha1hash?: string
    extension?: string
    mimeType?: string
    size?: number
    assetId?: string
    uploadId?: string
    path?: string
    url?: string
    source?: SanityAssetSourceData
}

export type SanityImageAsset = {
    _id: string
    _type: 'sanity.imageAsset'
    _createdAt: string
    _updatedAt: string
    _rev: string
    originalFilename?: string
    label?: string
    title?: string
    description?: string
    altText?: string
    sha1hash?: string
    extension?: string
    mimeType?: string
    size?: number
    assetId?: string
    uploadId?: string
    path?: string
    url?: string
    metadata?: SanityImageMetadata
    source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
    _type: 'sanity.imageMetadata'
    location?: Geopoint
    dimensions?: SanityImageDimensions
    palette?: SanityImagePalette
    lqip?: string
    blurHash?: string
    hasAlpha?: boolean
    isOpaque?: boolean
}

export type Geopoint = {
    _type: 'geopoint'
    lat?: number
    lng?: number
    alt?: number
}

export type Slug = {
    _type: 'slug'
    current?: string
    source?: string
}

export type SanityAssetSourceData = {
    _type: 'sanity.assetSourceData'
    name?: string
    id?: string
    url?: string
}

export type AllSanitySchemaTypes =
    | ProjectType
    | Brand
    | Personality
    | Post
    | StyleUp
    | Project
    | Contact
    | About
    | Settings
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageHotspot
    | SanityImageCrop
    | SanityFileAsset
    | SanityImageAsset
    | SanityImageMetadata
    | Geopoint
    | Slug
    | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "home"][0]{    _id,    _type,    overview,    title,  }
export type HomePageQueryResult = null
// Variable: slugsByTypeQuery
// Query: *[_type == $type && defined(slug.current)]{"slug": slug.current}
export type SlugsByTypeQueryResult = Array<{
    slug: string | null
}>
// Variable: allProjectTypesQuery
// Query: *[_type == "projectType" && !(_id in path("drafts.**"))]{    _id,    title,    "slug": slug.current,    "referenceCount": count(*[_type in ["project"] && references(^._id)]),  }
export type AllProjectTypesQueryResult = Array<{
    _id: string
    title: string | null
    slug: string | null
    referenceCount: number
}>
// Variable: sidebarFiltersQuery
// Query: {  "featuredCount": count(*[    _type == "project" &&    featured == true &&    !(_id in path("drafts.**"))  ]),  "allCount": count(*[    _type == "project" &&    !(_id in path("drafts.**"))  ]),  "projectTypes": *[    _type == "projectType" &&    !(_id in path("drafts.**"))  ] | order(title asc) {    _id,    title,    "slug": slug.current,    "referenceCount": count(*[      _type == "project" &&      !(_id in path("drafts.**")) &&      references(^._id)    ])  },  "personalities": *[    _type == "personality" &&    !(_id in path("drafts.**"))  ] | order(name asc) {    _id,    "title": name,    "slug": slug.current,    "referenceCount": count(*[      _type == "project" &&      !(_id in path("drafts.**")) &&      references(^._id)    ])  },  "brands": *[    _type == "brand" &&    !(_id in path("drafts.**"))  ] | order(name asc) {    _id,    "title": name,    "slug": slug.current,    "referenceCount": count(*[      _type == "project" &&      !(_id in path("drafts.**")) &&      references(^._id)    ])  }}
export type SidebarFiltersQueryResult = {
    featuredCount: number
    allCount: number
    projectTypes: Array<{
        _id: string
        title: string | null
        slug: string | null
        referenceCount: number
    }>
    personalities: Array<{
        _id: string
        title: string | null
        slug: string | null
        referenceCount: number
    }>
    brands: Array<{
        _id: string
        title: string | null
        slug: string | null
        referenceCount: number
    }>
}
// Variable: allStyleUpsQuery
// Query: *[_type == "styleUp" && !(_id in path("drafts.**"))]{  _id,  title,    coverImage{      alt,      ...,      asset->,    },}
export type AllStyleUpsQueryResult = Array<{
    _id: string
    title: null
    coverImage: null
}>
// Variable: projectBySlugQuery
// Query: *[    _type == "project" &&    !(_id in path("drafts.**")) &&    slug.current == $slug  ][0]{     _id,  _type,  title,  client,  date,  "slug": slug.current,  "projectType": projectType[]->{_id, title, "slug": slug.current},  featured,  "personalities": personalities[]->{_id, name, "slug": slug.current},  "brands": brands[]->{_id, name, "slug": slug.current},  gallery[]{    _key,    asset,    crop,    hotspot  },  "previewUrl": previewClip.asset->url,  videos[]{    _key,    "title": asset->originalFilename,    "fileUrl": asset->url,    thumbnail{      asset,      crop,      hotspot    }  },  videoUrls[]{    _key,    title,    url,    thumbnail{      asset,      crop,      hotspot    }  },  coverImage{    asset,    crop,    hotspot  },  description[],  credits[]{    role,    name,    link  },  orderRank  }
export type ProjectBySlugQueryResult = {
    _id: string
    _type: 'project'
    title: string | null
    client: string | null
    date: string | null
    slug: string | null
    projectType: Array<{
        _id: string
        title: string | null
        slug: string | null
    }> | null
    featured: boolean | null
    personalities: Array<{
        _id: string
        name: string | null
        slug: string | null
    }> | null
    brands: Array<{
        _id: string
        name: string | null
        slug: string | null
    }> | null
    gallery: Array<{
        _key: string
        asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        } | null
        crop: SanityImageCrop | null
        hotspot: SanityImageHotspot | null
    }> | null
    previewUrl: string | null
    videos: Array<{
        _key: string
        title: string | null
        fileUrl: string | null
        thumbnail: {
            asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            } | null
            crop: SanityImageCrop | null
            hotspot: SanityImageHotspot | null
        } | null
    }> | null
    videoUrls: Array<{
        _key: string
        title: null
        url: string | null
        thumbnail: {
            asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            } | null
            crop: SanityImageCrop | null
            hotspot: SanityImageHotspot | null
        } | null
    }> | null
    coverImage: {
        asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        } | null
        crop: SanityImageCrop | null
        hotspot: SanityImageHotspot | null
    } | null
    description: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
        }>
        style?: 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
    }> | null
    credits: Array<{
        role: string | null
        name: string | null
        link: string | null
    }> | null
    orderRank: string | null
} | null
// Variable: projectsQuery
// Query: *[    _type == "project" &&    !(_id in path("drafts.**")) &&    (      $filterType == "all" ||      ($filterType == "featured" && featured == true) ||      ($filterType == "projectType" && $filterId in projectType[]._ref) ||      ($filterType == "brand" && $filterId in brands[]._ref) ||      ($filterType == "personality" && $filterId in personalities[]._ref)    ) &&    (      !defined($cursorDate) ||      $cursorId == "" ||      date < $cursorDate ||      (date == $cursorDate && _id < $cursorId)    )  ]  | order(date desc, _id desc)  [0...$limit]{     _id,  _type,  title,  client,  date,  "slug": slug.current,  "projectType": projectType[]->{_id, title, "slug": slug.current},  featured,  "personalities": personalities[]->{_id, name, "slug": slug.current},  "brands": brands[]->{_id, name, "slug": slug.current},  gallery[]{    _key,    asset,    crop,    hotspot  },  "previewUrl": previewClip.asset->url,  videos[]{    _key,    "title": asset->originalFilename,    "fileUrl": asset->url,    thumbnail{      asset,      crop,      hotspot    }  },  videoUrls[]{    _key,    title,    url,    thumbnail{      asset,      crop,      hotspot    }  },  coverImage{    asset,    crop,    hotspot  },  description[],  credits[]{    role,    name,    link  },  orderRank  }
export type ProjectsQueryResult = Array<{
    _id: string
    _type: 'project'
    title: string | null
    client: string | null
    date: string | null
    slug: string | null
    projectType: Array<{
        _id: string
        title: string | null
        slug: string | null
    }> | null
    featured: boolean | null
    personalities: Array<{
        _id: string
        name: string | null
        slug: string | null
    }> | null
    brands: Array<{
        _id: string
        name: string | null
        slug: string | null
    }> | null
    gallery: Array<{
        _key: string
        asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        } | null
        crop: SanityImageCrop | null
        hotspot: SanityImageHotspot | null
    }> | null
    previewUrl: string | null
    videos: Array<{
        _key: string
        title: string | null
        fileUrl: string | null
        thumbnail: {
            asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            } | null
            crop: SanityImageCrop | null
            hotspot: SanityImageHotspot | null
        } | null
    }> | null
    videoUrls: Array<{
        _key: string
        title: null
        url: string | null
        thumbnail: {
            asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            } | null
            crop: SanityImageCrop | null
            hotspot: SanityImageHotspot | null
        } | null
    }> | null
    coverImage: {
        asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        } | null
        crop: SanityImageCrop | null
        hotspot: SanityImageHotspot | null
    } | null
    description: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
        }>
        style?: 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
    }> | null
    credits: Array<{
        role: string | null
        name: string | null
        link: string | null
    }> | null
    orderRank: string | null
}>
// Variable: featuredProjectsQuery
// Query: *[    _type == "project" &&    !(_id in path("drafts.**")) &&      featured == true &&    (      $cursorId == "" ||      coalesce(orderRank, "~~~~") > coalesce($cursorOrderRank, "~~~~") ||      (        coalesce(orderRank, "~~~~") == coalesce($cursorOrderRank, "~~~~") &&        _id > $cursorId      )    )  ]  | order(coalesce(orderRank, "~~~~") asc, _id asc)[0...$limit] {     _id,  _type,  title,  client,  date,  "slug": slug.current,  "projectType": projectType[]->{_id, title, "slug": slug.current},  featured,  "personalities": personalities[]->{_id, name, "slug": slug.current},  "brands": brands[]->{_id, name, "slug": slug.current},  gallery[]{    _key,    asset,    crop,    hotspot  },  "previewUrl": previewClip.asset->url,  videos[]{    _key,    "title": asset->originalFilename,    "fileUrl": asset->url,    thumbnail{      asset,      crop,      hotspot    }  },  videoUrls[]{    _key,    title,    url,    thumbnail{      asset,      crop,      hotspot    }  },  coverImage{    asset,    crop,    hotspot  },  description[],  credits[]{    role,    name,    link  },  orderRank  }
export type FeaturedProjectsQueryResult = Array<{
    _id: string
    _type: 'project'
    title: string | null
    client: string | null
    date: string | null
    slug: string | null
    projectType: Array<{
        _id: string
        title: string | null
        slug: string | null
    }> | null
    featured: boolean | null
    personalities: Array<{
        _id: string
        name: string | null
        slug: string | null
    }> | null
    brands: Array<{
        _id: string
        name: string | null
        slug: string | null
    }> | null
    gallery: Array<{
        _key: string
        asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        } | null
        crop: SanityImageCrop | null
        hotspot: SanityImageHotspot | null
    }> | null
    previewUrl: string | null
    videos: Array<{
        _key: string
        title: string | null
        fileUrl: string | null
        thumbnail: {
            asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            } | null
            crop: SanityImageCrop | null
            hotspot: SanityImageHotspot | null
        } | null
    }> | null
    videoUrls: Array<{
        _key: string
        title: null
        url: string | null
        thumbnail: {
            asset: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            } | null
            crop: SanityImageCrop | null
            hotspot: SanityImageHotspot | null
        } | null
    }> | null
    coverImage: {
        asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        } | null
        crop: SanityImageCrop | null
        hotspot: SanityImageHotspot | null
    } | null
    description: Array<{
        children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
        }>
        style?: 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
    }> | null
    credits: Array<{
        role: string | null
        name: string | null
        link: string | null
    }> | null
    orderRank: string | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
    interface SanityQueries {
        '\n  *[_type == "home"][0]{\n    _id,\n    _type,\n    overview,\n    title,\n  }\n': HomePageQueryResult
        '\n  *[_type == $type && defined(slug.current)]{"slug": slug.current}\n': SlugsByTypeQueryResult
        '\n  *[_type == "projectType" && !(_id in path("drafts.**"))]{\n    _id,\n    title,\n    "slug": slug.current,\n    "referenceCount": count(*[_type in ["project"] && references(^._id)]),\n  }\n': AllProjectTypesQueryResult
        '\n{\n  "featuredCount": count(*[\n    _type == "project" &&\n    featured == true &&\n    !(_id in path("drafts.**"))\n  ]),\n  "allCount": count(*[\n    _type == "project" &&\n    !(_id in path("drafts.**"))\n  ]),\n\n  "projectTypes": *[\n    _type == "projectType" &&\n    !(_id in path("drafts.**"))\n  ] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    "referenceCount": count(*[\n      _type == "project" &&\n      !(_id in path("drafts.**")) &&\n      references(^._id)\n    ])\n  },\n  "personalities": *[\n    _type == "personality" &&\n    !(_id in path("drafts.**"))\n  ] | order(name asc) {\n    _id,\n    "title": name,\n    "slug": slug.current,\n    "referenceCount": count(*[\n      _type == "project" &&\n      !(_id in path("drafts.**")) &&\n      references(^._id)\n    ])\n  },\n  "brands": *[\n    _type == "brand" &&\n    !(_id in path("drafts.**"))\n  ] | order(name asc) {\n    _id,\n    "title": name,\n    "slug": slug.current,\n    "referenceCount": count(*[\n      _type == "project" &&\n      !(_id in path("drafts.**")) &&\n      references(^._id)\n    ])\n  }\n}\n': SidebarFiltersQueryResult
        '\n*[_type == "styleUp" && !(_id in path("drafts.**"))\n]{\n  _id,\n  title,\n    coverImage{\n      alt,\n      ...,\n      asset->,\n    },}\n': AllStyleUpsQueryResult
        '\n  *[\n    _type == "project" &&\n    !(_id in path("drafts.**")) &&\n    slug.current == $slug\n  ][0]{\n   \n  _id,\n  _type,\n  title,\n  client,\n  date,\n  "slug": slug.current,\n  "projectType": projectType[]->{_id, title, "slug": slug.current},\n  featured,\n  "personalities": personalities[]->{_id, name, "slug": slug.current},\n  "brands": brands[]->{_id, name, "slug": slug.current},\n  gallery[]{\n    _key,\n    asset,\n    crop,\n    hotspot\n  },\n  "previewUrl": previewClip.asset->url,\n  videos[]{\n    _key,\n    "title": asset->originalFilename,\n    "fileUrl": asset->url,\n    thumbnail{\n      asset,\n      crop,\n      hotspot\n    }\n  },\n  videoUrls[]{\n    _key,\n    title,\n    url,\n    thumbnail{\n      asset,\n      crop,\n      hotspot\n    }\n  },\n  coverImage{\n    asset,\n    crop,\n    hotspot\n  },\n  description[],\n  credits[]{\n    role,\n    name,\n    link\n  },\n  orderRank\n\n  }\n': ProjectBySlugQueryResult
        '\n  *[\n    _type == "project" &&\n    !(_id in path("drafts.**")) &&\n    (\n      $filterType == "all" ||\n      ($filterType == "featured" && featured == true) ||\n      ($filterType == "projectType" && $filterId in projectType[]._ref) ||\n      ($filterType == "brand" && $filterId in brands[]._ref) ||\n      ($filterType == "personality" && $filterId in personalities[]._ref)\n    ) &&\n    (\n      !defined($cursorDate) ||\n      $cursorId == "" ||\n      date < $cursorDate ||\n      (date == $cursorDate && _id < $cursorId)\n    )\n  ]\n  | order(date desc, _id desc)\n  [0...$limit]{\n   \n  _id,\n  _type,\n  title,\n  client,\n  date,\n  "slug": slug.current,\n  "projectType": projectType[]->{_id, title, "slug": slug.current},\n  featured,\n  "personalities": personalities[]->{_id, name, "slug": slug.current},\n  "brands": brands[]->{_id, name, "slug": slug.current},\n  gallery[]{\n    _key,\n    asset,\n    crop,\n    hotspot\n  },\n  "previewUrl": previewClip.asset->url,\n  videos[]{\n    _key,\n    "title": asset->originalFilename,\n    "fileUrl": asset->url,\n    thumbnail{\n      asset,\n      crop,\n      hotspot\n    }\n  },\n  videoUrls[]{\n    _key,\n    title,\n    url,\n    thumbnail{\n      asset,\n      crop,\n      hotspot\n    }\n  },\n  coverImage{\n    asset,\n    crop,\n    hotspot\n  },\n  description[],\n  credits[]{\n    role,\n    name,\n    link\n  },\n  orderRank\n\n  }\n': ProjectsQueryResult
        '\n*[\n    _type == "project" &&\n    !(_id in path("drafts.**")) &&\n      featured == true &&\n    (\n      $cursorId == "" ||\n      coalesce(orderRank, "~~~~") > coalesce($cursorOrderRank, "~~~~") ||\n      (\n        coalesce(orderRank, "~~~~") == coalesce($cursorOrderRank, "~~~~") &&\n        _id > $cursorId\n      )\n    )\n  ]\n  | order(coalesce(orderRank, "~~~~") asc, _id asc)[0...$limit] {\n   \n  _id,\n  _type,\n  title,\n  client,\n  date,\n  "slug": slug.current,\n  "projectType": projectType[]->{_id, title, "slug": slug.current},\n  featured,\n  "personalities": personalities[]->{_id, name, "slug": slug.current},\n  "brands": brands[]->{_id, name, "slug": slug.current},\n  gallery[]{\n    _key,\n    asset,\n    crop,\n    hotspot\n  },\n  "previewUrl": previewClip.asset->url,\n  videos[]{\n    _key,\n    "title": asset->originalFilename,\n    "fileUrl": asset->url,\n    thumbnail{\n      asset,\n      crop,\n      hotspot\n    }\n  },\n  videoUrls[]{\n    _key,\n    title,\n    url,\n    thumbnail{\n      asset,\n      crop,\n      hotspot\n    }\n  },\n  coverImage{\n    asset,\n    crop,\n    hotspot\n  },\n  description[],\n  credits[]{\n    role,\n    name,\n    link\n  },\n  orderRank\n\n  }\n': FeaturedProjectsQueryResult
    }
}
